# Generated by Django 6.0.4 on 2026-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('packages', '0001_initial'),
        ('payments', '0001_initial'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Imetumika'), ('expired', 'Imeisha')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.mikrotikrouter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
