# Generated by Django 4.2.9 on 2026-06-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
