# Generated by Django 4.2.9 on 2026-07-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_mikrotikrouter_offline_alerted_at'),
        ('vouchers', '0003_voucher_sold_price_voucher_usage_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherRouterPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active — ipo kwenye router, bado haijafutwa'), ('removed', 'Imeondolewa — voucher ilitumika router nyingine'), ('failed', 'Imeshindwa kuundwa kwenye router hii')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_presences', to='routers.mikrotikrouter')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('voucher', 'router')},
            },
        ),
    ]
