# Generated by Django 4.2.9 on 2026-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_voucherrouterpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sync_missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
