# Generated by Django 6.0.4 on 2026-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Jina la device, mfano: Vodacom Device 1', max_length=100)),
                ('network', models.CharField(choices=[('vodacom', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'HaloPesa')], help_text='Network ya SIM card iliyowekwa', max_length=20, unique=True)),
                ('lipa_number', models.CharField(help_text='Namba ya lipa bili inayoonekana kwa wateja, mfano: 0744123456', max_length=20)),
                ('phone_number', models.CharField(help_text='Namba ya SIM card iliyomo kwenye device', max_length=20)),
                ('device_id', models.CharField(help_text='ID ya device inayotumwa na A7670 kwenye kila request', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu device hii')),
                ('is_active', models.BooleanField(default=True, help_text='Kama False, device hii haitapokea SMS wala kuonekana kwa clients')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Mara ya mwisho device iliwasiliana na server', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GSM Device',
                'verbose_name_plural': 'GSM Devices',
                'ordering': ['network'],
            },
        ),
    ]
