# Generated by Django 6.0.4 on 2026-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsmdevice',
            options={'ordering': ['network']},
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='device_id',
            field=models.CharField(help_text='ID ya device - lazima iwe sawa na inayotumwa na A7670', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='lipa_number',
            field=models.CharField(help_text='Namba ya lipa bili inayoonekana kwa wateja', max_length=20),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='network',
            field=models.CharField(choices=[('vodacom', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'HaloPesa')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='phone_number',
            field=models.CharField(help_text='Namba ya SIM card kwenye device', max_length=20),
        ),
    ]
