# Generated by Django 4.2.9 on 2026-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_gsmdevice_options_alter_gsmdevice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmdevice',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='lipa_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gsmdevice',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
