# Generated by Django 4.2.9 on 2026-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_gsmdevice_provisioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmdevice',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Admin enable/disable toggle (tofauti na 'status' ya provisioning)."),
        ),
    ]
