# Generated by Django 4.2.9 on 2026-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_gsmdevice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmdevice',
            name='battery_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gsmdevice',
            name='last_rssi',
            field=models.IntegerField(blank=True, help_text='GSM signal strength (CSQ raw value).', null=True),
        ),
        migrations.AddField(
            model_name='gsmdevice',
            name='on_backup_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gsmdevice',
            name='pending_restart',
            field=models.BooleanField(default=False, help_text='Amri ya soft-restart ya ESP32 inasubiri.'),
        ),
        migrations.AddField(
            model_name='gsmdevice',
            name='pending_sim_reset',
            field=models.BooleanField(default=False, help_text='Amri ya hard power-cycle ya SIM800C inasubiri.'),
        ),
    ]
