# Generated by Django 6.0.4 on 2026-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.IntegerField()),
                ('speed_up', models.CharField(default='2', max_length=10)),
                ('speed_down', models.CharField(default='2', max_length=10)),
                ('mikrotik_profile', models.CharField(max_length=50)),
                ('shared_users', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('client', 'price')},
            },
        ),
    ]
