# Generated by Django 4.2.9 on 2026-05-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_reference_prefix_client_identifier'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('client', 'name')},
        ),
    ]
