# Generated by Django 4.2.9 on 2026-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Masaa'), ('days', 'Siku')], default='hours', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_minutes',
            field=models.IntegerField(default=60, editable=False),
        ),
    ]
