# Generated by Django 6.0.4 on 2026-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_code', models.CharField(max_length=20)),
                ('network', models.CharField(choices=[('vodacom', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'HaloPesa'), ('unknown', 'Haijulikani')], default='unknown', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('raw_sms', models.TextField()),
                ('sms_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('processing', 'Inachakatwa'), ('completed', 'Imekamilika'), ('failed', 'Imeshindwa')], default='pending', max_length=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
