# Generated by Django 4.2.9 on 2026-05-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_reference_prefix_client_identifier'),
        ('packages', '0002_alter_package_unique_together'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_amount', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Package Price',
                'verbose_name_plural': 'Client Package Prices',
                'ordering': ['unique_amount'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='packages.package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='network',
            field=models.CharField(choices=[('vodacom', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'HaloPesa'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount'], name='payments_pa_amount_537f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['phone_number'], name='payments_pa_phone_n_483604_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['network'], name='payments_pa_network_b8ffca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddField(
            model_name='clientpackageprice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_prices', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientpackageprice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='packages.package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_package_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.clientpackageprice'),
        ),
    ]
