# Generated by Django 4.2.9 on 2026-07-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_client_mikrotik_permissions'),
        ('payments', '0002_clientpackageprice_remove_payment_reference_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('vodacom', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halo', 'HaloPesa'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('account_name', models.CharField(help_text='Jina la mmiliki wa lipa namba', max_length=100)),
                ('lipa_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('approved', 'Imekubaliwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='clients.client')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
