# Generated by Django 4.2.9 on 2026-08-07 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_mikrotik_permissions'),
        ('routers', '0004_mikrotikrouter_offline_alerted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Image'), ('video', 'Video (pre-roll)'), ('sponsored_access', 'Sponsored Free Access')], default='banner', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='ads/%Y/%m/')),
                ('click_url', models.URLField(blank=True)),
                ('sponsored_minutes', models.IntegerField(default=15, help_text='Dakika za access mtumiaji atapata akitazama ad hii (ad_type=sponsored_access pekee)')),
                ('cooldown_hours', models.IntegerField(default=24, help_text='Baada ya masaa mangapi MAC ile ile inaweza kupata sponsored access tena')),
                ('max_daily_grants_per_router', models.IntegerField(default=0, help_text='Kikomo cha jumla cha sponsored grants kwa siku kwa router (0 = hakuna kikomo)')),
                ('mikrotik_profile', models.CharField(default='sponsored_free', help_text='Jina la hotspot user profile kwenye MikroTik itakayotumika kwa sponsored access (TENGENEZA profile hii kwenye kila router kwanza, yenye rate-limit ya chini ili isishindane na wateja wanaolipia)', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Namba kubwa zaidi = kipaumbele zaidi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.advertiser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='clients.client')),
                ('routers', models.ManyToManyField(blank=True, related_name='ads', to='routers.mikrotikrouter')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(db_index=True, max_length=17)),
                ('minutes_granted', models.IntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_grants', to='ads.advertisement')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_grants', to='routers.mikrotikrouter')),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['client_mac', 'router', 'ad', 'granted_at'], name='ads_sponsor_client__6c1eb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(blank=True, db_index=True, max_length=17)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.advertisement')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='routers.mikrotikrouter')),
            ],
            options={
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['ad', 'router', 'shown_at'], name='ads_adimpre_ad_id_e6a785_idx')],
            },
        ),
    ]
