# Generated by Django 4.2.9 on 2026-08-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='client',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='mikrotik_profile',
            field=models.CharField(default='sponsored_free', help_text='Jina la hotspot user profile kwenye MikroTik itakayotumika kwa sponsored access (profile hii LAZIMA iwepo tayari kwenye kila router unayolenga)', max_length=100),
        ),
    ]
