# Generated by Django 6.0.4 on 2026-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Inasubiri'), ('taken', 'Imechukuliwa'), ('sent', 'Imetumwa'), ('failed', 'Imeshindwa')], default='queued', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Juu = muhimu zaidi')),
                ('retries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='payment',
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('queued', 'Inasubiri'), ('sent', 'Imetumwa'), ('failed', 'Imeshindwa')], default='queued', max_length=20),
        ),
    ]
