# Generated by Django 4.2.9 on 2026-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_outgoingsms_remove_smslog_payment_smslog_sent_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
        migrations.AlterField(
            model_name='outgoingsms',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
