# Generated by Django 6.0.4 on 2026-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroTikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(help_text='IP au domain ya MikroTik (MikroTik Cloud DDNS)', max_length=100)),
                ('api_port', models.IntegerField(default=8728)),
                ('api_username', models.CharField(default='admin', max_length=50)),
                ('api_password', models.CharField(max_length=100)),
                ('hotspot_interface', models.CharField(default='bridge', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
