# Generated by Django 6.0.4 on 2026-04-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('packages', '0001_initial'),
        ('payments', '0001_initial'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='host',
            field=models.CharField(help_text='VPN IP ya MikroTik (mfano: 10.0.0.2) au MikroTik Cloud DDNS', max_length=100),
        ),
        migrations.CreateModel(
            name='MikroTikJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='create_voucher', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('processing', 'Inachakatwa'), ('completed', 'Imekamilika'), ('failed', 'Imeshindwa')], default='pending', max_length=20)),
                ('voucher_code', models.CharField(blank=True, max_length=20)),
                ('customer_phone', models.CharField(max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('retries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routers.mikrotikrouter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
