# Generated by Django 4.2.9 on 2026-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_mikrotikrouter_updated_at_alter_mikrotikrouter_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='host',
            field=models.CharField(help_text='VPN IP (10.66.66.x) au DDNS', max_length=100),
        ),
    ]
