# Generated by Django 4.2.9 on 2026-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_alter_mikrotikrouter_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='offline_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
