# Generated by Django 4.2.9 on 2026-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_reference_prefix_client_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mikrotik_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Features za MikroTik ambazo client amepewa ruhusa'),
        ),
    ]
