# Generated by Django 4.2.9 on 2026-07-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_mikrotik_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Taarifa'), ('success', 'Mafanikio'), ('warning', 'Onyo'), ('error', 'Hitilafu')], default='info', max_length=10)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
